name: service-containers
on:
  push:
    branches:
      - master
jobs:
  test-services:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
    steps:
      - uses: actions/checkout@v4
      - run: ps u `pgrep redis`
